# Generated by Django 5.2.5 on 2025-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_created_at_organization_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('gold_processing', 'Oltin qayta ishlash'), ('silver_processing', 'Kumush qayta ishlash'), ('jewelry_making', 'Zargarlik buyumlari yaratish'), ('cleaning', 'Tozalash'), ('repair', "Ta'mirlash"), ('bank', 'Bank')], max_length=20),
        ),
    ]
