# Generated by Django 5.2.5 on 2026-02-15 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_alter_organization_created_at'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_process', 'Jarayonda'), ('completed', 'Yakunlandi'), ('canceled', 'Bekor qilindi')], db_index=True, default='in_process', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_in', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_out', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('gold_input', models.DecimalField(decimal_places=4, help_text='Input pure gold mass', max_digits=15)),
                ('iron_input', models.DecimalField(decimal_places=4, help_text='Input iron mass', max_digits=15)),
                ('scrap_output', models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Output scrap mass', max_digits=15, null=True)),
                ('iron_gold_output', models.DecimalField(blank=True, decimal_places=4, help_text='Output iron gold mass', max_digits=15, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'Coat Process',
                'verbose_name_plural': 'Coat Processes',
            },
        ),
        migrations.CreateModel(
            name='GoldDowngradeProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_process', 'Jarayonda'), ('completed', 'Yakunlandi'), ('canceled', 'Bekor qilindi')], db_index=True, default='in_process', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_in', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_out', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('gold_999_input', models.DecimalField(decimal_places=4, help_text='Mass of 999 gold input', max_digits=15)),
                ('gold_585_output', models.DecimalField(blank=True, decimal_places=4, help_text='Mass of 585 gold output', max_digits=15, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'Gold Downgrade Process',
                'verbose_name_plural': 'Gold Downgrade Processes',
            },
        ),
    ]
