# Generated by Django 5.2.5 on 2025-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_alter_process_options_process_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
