# Generated by Django 5.2.5 on 2025-09-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_organizationinventory_unique_together'),
        ('processes', '0003_alter_process_process_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processinput',
            name='material',
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('in process', 'In process'), ('completed', 'Completed')], default='completed', max_length=64),
        ),
        migrations.AddField(
            model_name='processinput',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.organizationinventory'),
            preserve_default=False,
        ),
    ]
