# Generated by Django 5.2.5 on 2025-10-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_parent_material_purity'),
        ('processes', '0003_process_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('inputs', models.ManyToManyField(related_name='template_inputs', to='materials.material')),
                ('outputs', models.ManyToManyField(related_name='template_outputs', to='materials.material')),
            ],
        ),
    ]
