# Generated by Django 5.2.5 on 2025-10-07 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_processtemplates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict)),
                ('type', models.CharField(choices=[('melting', 'Melting'), ('polishing', 'Polishing'), ('casting', 'Casting'), ('mixing', 'Mixing'), ('cutting', 'Cutting'), ('assembling', 'Assembling'), ('testing', 'Testing'), ('packaging', 'Packaging')], default='mixing', max_length=64)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.processtemplates')),
            ],
        ),
        migrations.AlterField(
            model_name='process',
            name='process_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='processes.processtype'),
            preserve_default=False,
        ),
    ]
