# Generated by Django 5.2.5 on 2025-10-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_parent_material_purity'),
        ('processes', '0005_processtype_alter_process_process_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessTemplates',
            new_name='ProcessTemplate',
        ),
    ]
