# Generated by Django 5.2.5 on 2025-10-07 22:06

import apps.processes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_rename_processtemplates_processtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtype',
            name='name',
            field=models.JSONField(default=apps.processes.models.default_name),
        ),
    ]
