# Generated by Django 5.2.5 on 2025-10-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_alter_processtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinput',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
    ]
