# Generated by Django 5.2.5 on 2025-10-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_alter_processinput_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.processtype'),
        ),
    ]
