# Generated by Django 5.2.5 on 2025-10-28 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_material_parent'),
        ('processes', '0009_alter_process_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinput',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material'),
        ),
        migrations.AlterField(
            model_name='processoutput',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
    ]
