# Generated by Django 5.2.5 on 2025-10-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_alter_processinput_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processinput',
            old_name='product',
            new_name='material',
        ),
    ]
