# Generated by Django 5.2.5 on 2025-10-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_material_parent'),
        ('processes', '0011_rename_product_processinput_material'),
        ('products', '0008_product_purity_delete_productgenealogy'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinput',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='processinput',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.material'),
        ),
    ]
