# Generated by Django 5.2.5 on 2025-10-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_processinput_product_alter_processinput_material'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='projects.project'),
        ),
    ]
