# Generated by Django 5.2.5 on 2025-11-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0013_alter_process_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='total_in',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='total_out',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
