# Generated by Django 5.2.5 on 2025-11-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_material_mixes_with_gold'),
        ('processes', '0014_process_total_in_process_total_out'),
        ('products', '0008_product_purity_delete_productgenealogy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinput',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.material'),
        ),
        migrations.AlterField(
            model_name='processinput',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
