# Generated by Django 5.2.5 on 2025-11-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0015_alter_processinput_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='total_in',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='total_out',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='processinput',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='processoutput',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
