# Generated by Django 5.2.5 on 2025-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_created_at'),
        ('processes', '0016_alter_process_total_in_alter_process_total_out_and_more'),
        ('projects', '0002_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('in process', 'In process'), ('completed', 'Completed')], db_index=True, default='in process', max_length=64),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['organization', 'status'], name='proc_org_status_idx'),
        ),
    ]
