# Generated by Django 5.2.5 on 2026-01-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0017_alter_process_created_at_alter_process_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtype',
            name='type',
            field=models.CharField(choices=[('melting', 'Melting'), ('coat', 'Coat'), ('polishing', 'Polishing'), ('casting', 'Casting'), ('mixing', 'Mixing'), ('cutting', 'Cutting'), ('assembling', 'Assembling'), ('testing', 'Testing'), ('packaging', 'Packaging')], default='mixing', max_length=64),
        ),
    ]
