# Generated by Django 5.2.5 on 2026-01-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0018_alter_processtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='can_cause_loss',
            field=models.BooleanField(default=False, help_text="Bu jarayon material yo'qotilishiga olib kelishi mumkinligini ko'rsatadi."),
        ),
    ]
