# Generated by Django 5.2.5 on 2026-01-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_material_is_scrap'),
        ('processes', '0019_processtype_can_cause_loss'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_all_material', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
        ),
        migrations.AlterField(
            model_name='processtemplate',
            name='inputs',
            field=models.ManyToManyField(related_name='template_inputs', to='processes.processtemplateitem'),
        ),
        migrations.AlterField(
            model_name='processtemplate',
            name='outputs',
            field=models.ManyToManyField(related_name='template_outputs', to='processes.processtemplateitem'),
        ),
    ]
