# Generated by Django 5.2.5 on 2026-01-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_material_is_scrap'),
        ('processes', '0020_processtemplateitem_alter_processtemplate_inputs_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processtemplateitem',
            unique_together={('material', 'use_all_material')},
        ),
    ]
