# Generated by Django 5.2.5 on 2026-01-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0021_alter_processtemplateitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtype',
            name='type',
            field=models.CharField(choices=[('melting', 'Melting'), ('coat', 'Coat'), ('mixing', 'Mixing'), ('polishing', 'Polishing'), ('casting', 'Casting'), ('cutting', 'Cutting'), ('assembling', 'Assembling'), ('testing', 'Testing'), ('packaging', 'Packaging')], default='mixing', max_length=64),
        ),
    ]
