# Generated by Django 5.2.5 on 2026-01-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_material_is_scrap'),
        ('processes', '0022_alter_processtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtemplate',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='processtemplate',
            name='outputs',
        ),
        migrations.CreateModel(
            name='ProcessTemplateInputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('base_gold', 'Base Gold'), ('additive_gold', 'Additive Gold'), ('metal', 'Metal'), ('auxiliary', 'Auxiliary'), ('composite', 'Composite'), ('pure_gold', 'Pure Gold'), ('scrap', 'Scrap'), ('loss', 'Loss')], max_length=127)),
                ('use_all_material', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_inputs', to='processes.processtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessTemplateOutputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('base_gold', 'Base Gold'), ('additive_gold', 'Additive Gold'), ('metal', 'Metal'), ('auxiliary', 'Auxiliary'), ('composite', 'Composite'), ('pure_gold', 'Pure Gold'), ('scrap', 'Scrap'), ('loss', 'Loss')], max_length=127)),
                ('use_all_material', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_outputs', to='processes.processtemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessTemplateItem',
        ),
    ]
