# Generated by Django 5.2.5 on 2026-01-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0023_remove_processtemplate_inputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtype',
            name='type',
            field=models.CharField(choices=[('melting', 'Melting'), ('coat', 'Coat'), ('mixing', 'Mixing'), ('alloy', 'Alloy'), ('polishing', 'Polishing'), ('casting', 'Casting'), ('cutting', 'Cutting'), ('assembling', 'Assembling'), ('testing', 'Testing'), ('packaging', 'Packaging')], default='mixing', max_length=64),
        ),
    ]
