# Generated by Django 5.2.5 on 2025-09-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('pcs', 'Pieces'), ('ct', 'Carat')], max_length=10)),
            ],
        ),
    ]
