# Generated by Django 5.2.5 on 2025-10-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_created_at_material_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.material'),
        ),
        migrations.AddField(
            model_name='material',
            name='purity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
