# Generated by Django 5.2.5 on 2025-10-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_parent_material_purity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='parent',
        ),
    ]
