# Generated by Django 5.2.5 on 2025-10-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_material_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='mixes_with_gold',
            field=models.BooleanField(default=False, help_text='Whether this material mixes with gold (affects purity calculation).'),
        ),
    ]
