# Generated by Django 5.2.5 on 2025-11-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_material_mixes_with_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='purity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
