# Generated by Django 5.2.5 on 2026-01-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_material_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_scrap',
            field=models.BooleanField(default=False, help_text='Whether this material is considered scrap.'),
        ),
    ]
