# Generated by Django 5.2.5 on 2025-09-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='confirmed_by_receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confirmed_by_sender',
        ),
    ]
