# Generated by Django 5.2.5 on 2025-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
