# Generated by Django 5.2.5 on 2025-09-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('transactions', '0004_remove_transaction_confirmed_by_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='material',
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.organizationinventory'),
            preserve_default=False,
        ),
    ]
