# Generated by Django 5.2.5 on 2025-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_created_at'),
        ('products', '0011_product_prod_org_proj_mat_idx_and_more'),
        ('projects', '0002_alter_project_created_at'),
        ('transactions', '0004_alter_transactionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sender', 'receiver'], name='tx_sender_receiver_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['transaction', 'product'], name='tx_item_tx_prod_idx'),
        ),
    ]
