# Generated by Django 5.2.5 on 2025-09-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationinventory',
            unique_together=set(),
        ),
    ]
