# Generated by Django 5.2.5 on 2026-02-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_alter_organization_created_at'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(choices=[('gold_999', 'Gold 999'), ('gold_585', 'Gold 585'), ('iron', 'Iron'), ('iron_gold', 'Iron Gold'), ('scrap', 'Scrap')], db_index=True, max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('purity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('is_composite', models.BooleanField(default=False, help_text='Indicates if product contains non-gold materials (e.g., iron core).')),
                ('pure_gold', models.DecimalField(decimal_places=4, default=0, help_text='Actual mass of pure gold within this product in grams.', max_digits=15)),
                ('source_description', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'project', 'material'], name='prod_org_proj_mat_idx'), models.Index(fields=['organization', 'material'], name='prod_org_mat_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'project', 'material'), name='uniq_org_proj_mat')],
            },
        ),
    ]
