# Generated by Django 5.2.5 on 2025-10-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_parent_material_purity'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='ProductGenealogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(help_text='Parent contribution as fraction (0..1)')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_parents', to='products.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_children', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'parent')},
            },
        ),
    ]
