# Generated by Django 5.2.5 on 2025-10-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_parent_material_purity'),
        ('products', '0002_product_source_description_alter_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgenealogy',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_parents', to='materials.material'),
        ),
    ]
