# Generated by Django 5.2.5 on 2025-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_parent_material_purity'),
        ('products', '0003_alter_productgenealogy_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgenealogy',
            old_name='parent',
            new_name='material',
        ),
        migrations.AlterUniqueTogether(
            name='productgenealogy',
            unique_together={('product', 'material')},
        ),
        migrations.AlterField(
            model_name='productgenealogy',
            name='percent',
            field=models.FloatField(help_text='Material contribution as fraction (0..1)'),
        ),
    ]
