# Generated by Django 5.2.5 on 2025-10-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_parent_material_purity'),
        ('products', '0004_rename_parent_productgenealogy_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgenealogy',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_children', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='productgenealogy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_parents', to='products.product'),
        ),
    ]
