# Generated by Django 5.2.5 on 2025-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productgenealogy_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
