# Generated by Django 5.2.5 on 2025-10-18 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_quantity'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
