# Generated by Django 5.2.5 on 2025-10-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='ProductGenealogy',
        ),
    ]
