# Generated by Django 5.2.5 on 2025-11-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_purity_delete_productgenealogy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_composite',
            field=models.BooleanField(default=False, help_text='Indicates if product contains non-gold materials (e.g., iron core).'),
        ),
        migrations.AddField(
            model_name='product',
            name='pure_gold',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Actual mass of pure gold within this product in grams.', max_digits=10),
        ),
    ]
