# Generated by Django 5.2.5 on 2025-11-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_composite_product_pure_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pure_gold',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Actual mass of pure gold within this product in grams.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='purity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
