# Generated by Django 5.2.5 on 2025-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_material_created_at'),
        ('organizations', '0005_alter_organization_created_at'),
        ('products', '0010_alter_product_pure_gold_alter_product_purity_and_more'),
        ('projects', '0002_alter_project_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'project', 'material'], name='prod_org_proj_mat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'material'], name='prod_org_mat_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organization', 'project', 'material'), name='uniq_org_proj_mat'),
        ),
    ]
